{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-project-chart.fullname" . }}
  labels:
    {{- include "my-project-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- /* This section dynamically builds the TLS configuration */}}
  {{- $hasTls := false }}
  {{- range .Values.ingress.hosts }}
    {{- if and .tls .tls.enabled }}
      {{- $hasTls = true }}
    {{- end }}
  {{- end }}
  {{- if $hasTls }}
  tls:
    {{- range .Values.ingress.hosts }}
    {{- if and .tls .tls.enabled }}
    - hosts:
        - {{ .host | quote }}
      secretName: {{ .tls.secretName }}
    {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- /* This section creates a rule for each host defined in values.yaml */}}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .path | default "/" }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .service.name }}
                port:
                  number: {{ .service.port }}
    {{- end }}
{{- end }}