{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "k8s-dataflow-project.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-dataflow-project.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.hosts }}
    {{- if .tls.enabled }}
    - hosts:
        - {{ .host }}
      secretName: {{ .tls.secretName }}
    {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
        - path: {{ .path }}
          pathType: {{ .pathType }}
          backend:
            service:
              name: {{ .service.name }}
              port:
                number: {{ .service.port }}
    {{- end }}
{{- end }}