{{- if .Values.spark.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-dataflow-project.fullname" . }}-spark-config
  labels:
    {{- include "k8s-dataflow-project.labels" . | nindent 4 }}
data:
  # Spark properties for spark-defaults.conf
  spark-defaults.conf: |
    {{- .Values.spark.properties | nindent 4 }}
  # S3 credentials are now passed directly via spark.kubernetes.driver.env and spark.kubernetes.executor.env
  # in spark-defaults.conf, so they don't need to be explicitly in this configmap data block.
  # They will be read from the secret directly by Spark Kubernetes.
{{- end }}