# ./k8s-dataflow-project/Chart.yaml

apiVersion: v2
name: k8s-dataflow-project
description: A Helm chart for deploying the transaction dataflow PoC on Kubernetes.
type: application
version: 0.2.0 # Incremented version for new features
appVersion: "1.1.0" # Incremented app version

dependencies:
  # --- CI/CD ---
  - name: jenkins
    version: "4.9.2" # Using the official Jenkins chart
    repository: "https://charts.jenkins.io"
    alias: jenkins

  # --- Metrics & Monitoring ---
  - name: grafana
    version: "8.3.4" # Using the official Grafana chart
    repository: "https://grafana.github.io/helm-charts"
    alias: grafana

  - name: influxdb2
    # This chart deploys InfluxDB v2.x
    version: "2.3.1"
    repository: "https://helm.influxdata.com/"
    # We use a simpler alias for easier reference in values.yaml
    alias: influxdb

  # --- Existing Data & Messaging Services ---
  - name: minio
    version: "14.6.1"
    repository: "https://charts.bitnami.com/bitnami"
    alias: minio

  - name: kafka
    version: "29.1.0"
    repository: "https://charts.bitnami.com/bitnami"
    alias: kafka

  - name: redis
    version: "19.1.0"
    repository: "https://charts.bitnami.com/bitnami"
    alias: redis

  # --- Your Custom Local Sub-chart ---
  - name: hive-metastore
    version: "0.1.0"
    repository: "file://charts/hive-metastore"
    alias: hiveMetastore

  - name: postgresql
    version: "15.5.4"
    repository: "https://charts.bitnami.com/bitnami"
    alias: hivePostgresql # Database for Hive Metastore
    condition: hiveMetastore.database.create

  # --- Custom Local Sub-chart ---
  - name: hive-metastore
    version: "0.1.0"
    repository: "file://charts/hive-metastore"
    alias: hiveMetastore